services:
    Derhaeuptling\ContaoImmoscout24\ExpressionLanguage\RealEstateFilterEvaluator:

    # entity repositories
    Derhaeuptling\ContaoImmoscout24\Repository\AccountRepository:
        arguments:
            - '@doctrine'
        tags:
            - { name: 'doctrine.repository_service' }

    Derhaeuptling\ContaoImmoscout24\Repository\RealEstateRepository:
        arguments:
            - '@doctrine'
            - '@Derhaeuptling\ContaoImmoscout24\ExpressionLanguage\RealEstateFilterEvaluator'
        tags:
            - { name: 'doctrine.repository_service' }

    Derhaeuptling\ContaoImmoscout24\Repository\AttachmentRepository:
        arguments:
            - '@doctrine'
        tags:
            - { name: 'doctrine.repository_service' }

    # synchronization & scraping
    Derhaeuptling\ContaoImmoscout24\Synchronizer\SynchronizerFactory:
        arguments:
            - '@doctrine'
            - '@Derhaeuptling\ContaoImmoscout24\Repository\RealEstateRepository'

    Derhaeuptling\ContaoImmoscout24\Command\SyncRealEstateCommand:
        arguments:
            - '@Derhaeuptling\ContaoImmoscout24\Synchronizer\SynchronizerFactory'
            - '@Derhaeuptling\ContaoImmoscout24\Repository\AccountRepository'
        tags:
            - { name: 'console.command', command: 'immoscout24:sync' }

    Derhaeuptling\ContaoImmoscout24\Command\ScrapeAttachmentsCommand:
        arguments:
            - '@Derhaeuptling\ContaoImmoscout24\Repository\AttachmentRepository'
            - '@Derhaeuptling\ContaoImmoscout24\Synchronizer\FileScraper'
            - '@doctrine'
            - '%kernel.project_dir%'
        tags:
            - { name: 'console.command', command: 'immoscout24:scrape-attachments' }

    Derhaeuptling\ContaoImmoscout24\Synchronizer\FileScraper:
        arguments:
            - '%kernel.project_dir%'

    # backend
    Derhaeuptling\ContaoImmoscout24\EventListener\DataContainer\Account:
        arguments:
            - '@Derhaeuptling\ContaoImmoscout24\Repository\AccountRepository'
            - '@contao.translation.translator'
        tags:
            - { name: 'terminal42_service_annotation' }

    Derhaeuptling\ContaoImmoscout24\EventListener\DataContainer\Module:
        arguments:
            - '@Derhaeuptling\ContaoImmoscout24\Repository\AccountRepository'
            - '@Derhaeuptling\ContaoImmoscout24\ExpressionLanguage\RealEstateFilterEvaluator'
        tags:
            - { name: 'terminal42_service_annotation' }

    # frontend
    Derhaeuptling\ContaoImmoscout24\Controller\FrontendModule\RealEstateListController:
        arguments:
            - '@Derhaeuptling\ContaoImmoscout24\Repository\AccountRepository'
            - '@Derhaeuptling\ContaoImmoscout24\Repository\RealEstateRepository'
            - '@contao.translation.translator'
        tags:
            - { name: 'contao.frontend_module', category: 'immoscout24', type: 'immoscout24_real_estate_list' }

    Derhaeuptling\ContaoImmoscout24\Controller\FrontendModule\RealEstateReaderController:
        tags:
            - { name: 'contao.frontend_module', category: 'immoscout24', type: 'immoscout24_real_estate_reader' }
        arguments:
            - '@doctrine'
            - '@contao.translation.translator'
