services:
    Derhaeuptling\ContaoImmoscout24\ExpressionLanguage\RealEstateFilterEvaluator:

    # entity repositories
    Derhaeuptling\ContaoImmoscout24\Repository\AccountRepository:
        arguments:
            - '@doctrine'
        tags:
            - { name: 'doctrine.repository_service' }

    Derhaeuptling\ContaoImmoscout24\Repository\RealEstateRepository:
        arguments:
            - '@doctrine'
            - '@Derhaeuptling\ContaoImmoscout24\ExpressionLanguage\RealEstateFilterEvaluator'
        tags:
            - { name: 'doctrine.repository_service' }

    Derhaeuptling\ContaoImmoscout24\Repository\AttachmentRepository:
        arguments:
            - '@doctrine'
        tags:
            - { name: 'doctrine.repository_service' }

    # synchronization & scraping
    Derhaeuptling\ContaoImmoscout24\Synchronizer\SynchronizerFactory:
        arguments:
            - '@doctrine'
            - '@Derhaeuptling\ContaoImmoscout24\Repository\RealEstateRepository'
            - '@contao.filesystem.virtual.immoscout_attachments'

    Derhaeuptling\ContaoImmoscout24\Command\SyncRealEstateCommand:
        arguments:
            - '@Derhaeuptling\ContaoImmoscout24\Synchronizer\SynchronizerFactory'
            - '@Derhaeuptling\ContaoImmoscout24\Repository\AccountRepository'
            - '@Derhaeuptling\ContaoImmoscout24\Repository\RealEstateRepository'
            - '@doctrine.orm.entity_manager'
            - '@contao.filesystem.virtual.immoscout_attachments'
        tags:
            - { name: 'console.command', command: 'immoscout24:sync' }

    # backend
    Derhaeuptling\ContaoImmoscout24\EventListener\DataContainer\Account:
        arguments:
            - '@Derhaeuptling\ContaoImmoscout24\Repository\AccountRepository'
            - '@contao.translation.translator'
            - '@request_stack'
            - '@router'
        tags:
            - { name: 'terminal42_service_annotation' }

    Derhaeuptling\ContaoImmoscout24\EventListener\DataContainer\Module:
        arguments:
            - '@Derhaeuptling\ContaoImmoscout24\Repository\AccountRepository'
            - '@Derhaeuptling\ContaoImmoscout24\ExpressionLanguage\RealEstateFilterEvaluator'
        tags:
            - { name: 'terminal42_service_annotation' }

    Derhaeuptling\ContaoImmoscout24\Controller\BackEnd\AccessTokenController:
        public: true
        arguments:
            - '@security.helper'
            - '@Derhaeuptling\ContaoImmoscout24\Repository\AccountRepository'
            - '@doctrine.orm.entity_manager'
            - '@contao.translation.translator'
            - '@contao.framework'
        calls:
            - [setContainer, ['@service_container']]

    # frontend
    Derhaeuptling\ContaoImmoscout24\Controller\FrontendModule\RealEstateListController:
        arguments:
            - '@Derhaeuptling\ContaoImmoscout24\Repository\AccountRepository'
            - '@Derhaeuptling\ContaoImmoscout24\Repository\RealEstateRepository'
            - '@contao.image.studio'
            - '@contao.filesystem.virtual.immoscout_attachments'
            - '@contao.translation.translator'
        tags:
            - { name: 'contao.frontend_module', category: 'immoscout24', type: 'immoscout24_real_estate_list' }

    Derhaeuptling\ContaoImmoscout24\Controller\FrontendModule\RealEstateReaderController:
        arguments:
            - '@Derhaeuptling\ContaoImmoscout24\Repository\RealEstateRepository'
            - '@contao.image.studio'
            - '@contao.filesystem.virtual.immoscout_attachments'
            - '@contao.translation.translator'
        tags:
            - { name: 'contao.frontend_module', category: 'immoscout24', type: 'immoscout24_real_estate_reader' }
