services:
    # entity repositories
    Derhaeuptling\ContaoImmoscout24\Repository\AccountRepository:
        arguments:
            - '@doctrine'
        tags:
            - { name: 'doctrine.repository_service' }

    Derhaeuptling\ContaoImmoscout24\Repository\RealEstateRepository:
        arguments:
            - '@doctrine'
        tags:
            - { name: 'doctrine.repository_service' }

    # synchronization
    Derhaeuptling\ContaoImmoscout24\Synchronizer\SynchronizerFactory:
        arguments:
            - '@doctrine'
            - '@Derhaeuptling\ContaoImmoscout24\Repository\RealEstateRepository'

    Derhaeuptling\ContaoImmoscout24\Command\SyncRealEstateCommand:
        arguments:
            - '@Derhaeuptling\ContaoImmoscout24\Synchronizer\SynchronizerFactory'
            - '@Derhaeuptling\ContaoImmoscout24\Repository\AccountRepository'
        tags:
            - { name: 'console.command', command: 'immoscout24:sync' }

    # backend
    Derhaeuptling\ContaoImmoscout24\EventListener\Account:
        arguments:
            - '@Derhaeuptling\ContaoImmoscout24\Repository\AccountRepository'
            - '@contao.translation.translator'
        tags:
            - { name: 'contao.callback', table: 'tl_immoscout24_account', target: 'list.label.label' }

    # frontend
    Derhaeuptling\ContaoImmoscout24\Controller\FrontendModule\RealEstateListController:
        tags:
            - { name: 'contao.frontend_module', category: 'immoscout24', type: 'immoscout24_real_estate_list' }
        arguments:
            - '@doctrine'
            - '@contao.translation.translator'

    Derhaeuptling\ContaoImmoscout24\Controller\FrontendModule\RealEstateReaderController:
        tags:
            - { name: 'contao.frontend_module', category: 'immoscout24', type: 'immoscout24_real_estate_reader' }
        arguments:
            - '@doctrine'
            - '@contao.translation.translator'
