name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout 
      uses: actions/checkout@v1
    
    - name: Install the dependencies
      run: composer update --no-interaction --no-suggest
              
    - name: Run the unit tests
      run: vendor/bin/phpunit --colors=always
